### ISSUE TITLE
reset/clear apollo store

### ISSUE THREAD

**Issue by genox** [NexonTreeHouse/qwik-graphql-client#6]
Hi,

I use this client to make authenticated requests. I managed to setup middleware for bearer tokens, refresh, etc and it works just fine. It's a pleasure to work with, once things are setup correctly with the codegen.

However, I wonder how to clear the apollo cache when a user logs out or when a session resets or for some other reason. I don't think this method is exposed in the provider. Since I am using middleware, the Apollo Client object is inside of a qwik component, so there is no easy access to the client directly, too. I couldn't get middleware to work with the Apollo Client object residing outside of a component due to it no being able to serialise (or so I think). It only seems to work as intended when encapsulated.

Do you have a suggestion on how I could achieve my goal? I was thinking about using a signal, tracking it and calling the method on the client object directly whenever the value changes, since I would probably get access from within the provider component itself, but that does feel quite hacky.

Any hints would be appreciated.

**Comment by NexonTreeHouse** [comment]
There is a hook called `useApolloClient` that is exported, which should return the client generated in the provider.  I haven't really used it, it might be a little funky, so let me know if you run into any troubles with it.

Something like this could potentially work for your issue.
```ts
const { client } = useApolloClient();

await client?.clearStore();
```

**Comment by genox** [comment]
I will try that, thank you.

**Comment by genox** [comment]
It seems like the client and its methods returned by the hook are not serializable. Can't use any of the functions in useTask$ hooks. Tried my luck with wrapping in all sorts of different qwik functions but nothing worked. Maybe the client needs to be wrapped in noSerializable() before returning from the useApolloClient hook? Are you using it like that in some place already?

**Comment by genox** [comment]
Scrap that, I imported the wrong useApolloClient
